version: "3.7"

services:
  miro_table_client:
    container_name: miro_table_client_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    networks:
      - miro_net

networks:
  miro_net:
    name: miro_net
